### ISSUE TITLE
`word_to_ix` on the wrong input?

### ISSUE THREAD

**Issue by sarahmonod** [rguthrie3/DeepLearningForNLPInPytorch#3]
Hi,

I'm confused with the way you build `word_to_ix` here: https://github.com/rguthrie3/DeepLearningForNLPInPytorch/blame/master/Deep%20Learning%20for%20Natural%20Language%20Processing%20with%20Pytorch.ipynb#L1448

Is there any reason of why you don't use the `vocab` or `set(raw_text)` instead, like you do here: https://github.com/rguthrie3/DeepLearningForNLPInPytorch/blame/master/Deep%20Learning%20for%20Natural%20Language%20Processing%20with%20Pytorch.ipynb#L1298 ??

**Comment by rguthrie3** [comment]
You're right.  It should have been set(raw_text).  THis doesn't affect correctness, it just makes the size of the embedding table be the number of tokens, not the number of types (with a lot of unused embeddings in the table).  Obviously this is bad for any real data set.  I've fixed it.
